### ISSUE TITLE
JavaDoc comments for all classes

### ISSUE THREAD

**Issue by CFuterman** [SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018#89] opened 2018-02-22 11:31 UTC

**Comment by SamanthaDawsonBanks** [comment] 2018-02-23 12:55
I'm terrible at documentation ("bad Dave no doc = bad coder") if anyone is available and looking for somersaulting to do can they give me a hand / some pointers

**Comment by CFuterman** [comment] 2018-02-23 18:33
I'm happy to help give a hand at the documentation. On the next meeting, I am happy to stay a bit longer in order to give a hand in documentation, whether it is just to template some things for you to fill in or sit with you and do it with you. Let me know.

**Comment by SamanthaDawsonBanks** [comment] 2018-03-11 17:01
duplicate of #17

**Closed as completed by SamanthaDawsonBanks** 2018-03-11 17:01 UTC
Labels: Documentation
